# Generated by Django 2.2.1 on 2021-11-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credits',
            field=models.IntegerField(default=6),
        ),
    ]
