# Generated by Django 2.2.1 on 2021-12-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credits',
            field=models.FloatField(default=6),
        ),
    ]
