# Generated by Django 2.2.1 on 2022-05-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220523_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterestSelection',
        ),
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=models.TextField(blank=True),
        ),
    ]
