# Generated by Django 3.2.9 on 2022-05-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_1', models.CharField(choices=[('sport', 'Sport'), ('art', 'Art'), ('music', 'Music'), ('cooking', 'Cooking'), ('agriculture', 'Agriculture'), ('handicraft', 'Handicraft'), ('dance', 'Dance'), ('music', 'Music'), ('cinema', 'Cinema'), ('fashion', 'Fashion')], max_length=11)),
                ('interest_2', models.CharField(choices=[('sport', 'Sport'), ('art', 'Art'), ('music', 'Music'), ('cooking', 'Cooking'), ('agriculture', 'Agriculture'), ('handicraft', 'Handicraft'), ('dance', 'Dance'), ('music', 'Music'), ('cinema', 'Cinema'), ('fashion', 'Fashion')], max_length=11)),
                ('interest_3', models.CharField(choices=[('sport', 'Sport'), ('art', 'Art'), ('music', 'Music'), ('cooking', 'Cooking'), ('agriculture', 'Agriculture'), ('handicraft', 'Handicraft'), ('dance', 'Dance'), ('music', 'Music'), ('cinema', 'Cinema'), ('fashion', 'Fashion')], max_length=11)),


            ],
        ),
    ]
