# Generated by Django 2.2.1 on 2022-05-27 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_interestselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
