# Generated by Django 2.2.1 on 2022-05-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_historicalprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprofile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical profile', 'verbose_name_plural': 'historical profiles'},
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
