# Generated by Django 2.2.1 on 2022-01-01 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='location',
        ),
    ]
