# Generated by Django 2.2.1 on 2022-05-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220511_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='interest',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=models.TextField(blank=True),
        ),
    ]
