# Generated by Django 2.2.1 on 2022-05-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220527_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='range',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='range',
            field=models.IntegerField(default=1),
        ),
    ]
