# Generated by Django 2.2.1 on 2022-05-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220511_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='isEmployee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='isEmployee',
            field=models.BooleanField(default=False),
        ),
    ]
