# Generated by Django 3.2.9 on 2022-05-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_historicalprofile'),
        ('users', '0006_interestselection'),
    ]

    operations = [
    ]
