# Generated by Django 2.2.1 on 2022-05-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220516_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprofile',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical profile'},
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
