# Generated by Django 2.2.1 on 2022-01-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reserved',
            field=models.IntegerField(default=0),
        ),
    ]
