# Generated by Django 2.2.1 on 2022-05-23 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220519_2311'),
        ('users', '0008_auto_20220516_2043'),
    ]

    operations = [
    ]
