version: '3.8'
 
services:
  # nginx:
  #   container_name: core_web
  #    restart: on-failure
  #   image: nginx:stable
  #   volumes:
  #     - nginx_secrets:/etc/letsencrypt
  #     - ./nginx/user_conf.d:/etc/nginx/user_conf.d
  #   ports:
  #     - "80:80"
  #     - "443:443"

  #   depends_on:
  #     - web
  elasticsearch:
    container_name: core_search
    image: blacktop/elasticsearch:6.7.1
           
  web:
   container_name: core_eventify
   build: .
   restart: always
   env_file: ./web/.env
  #  command: python manage.py runserver 0.0.0.0:8000
   volumes:
     - .:/web
     - static_volume:/web/static
   depends_on:
     - db 
     - elasticsearch

   ports:
     - 80:8000
  
  db:
    container_name: core_db
    image: postgres:14.1-alpine
    env_file:  ./web/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
     - 5433:5432


volumes:
  static_volume:
  postgres_data:
  nginx_secrets: