# Generated by Django 2.2.1 on 2021-11-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0006_registerevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerevent',
            old_name='service',
            new_name='post',
        ),
    ]
