# Generated by Django 2.2.1 on 2021-11-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0008_auto_20211122_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='eventdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='eventdate',
            field=models.DateField(null=True),
        ),
    ]
