# Generated by Django 2.2.1 on 2021-11-22 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0011_post_eventdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='eventtime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='service',
            name='eventtime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='eventdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='service',
            name='eventdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
