# Generated by Django 2.2.1 on 2021-11-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0014_auto_20211123_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerevent',
            old_name='approved_comment',
            new_name='approved_register',
        ),
        migrations.RenameField(
            model_name='registerservice',
            old_name='approved_comment',
            new_name='approved_register',
        ),
    ]
