# Generated by Django 2.2.1 on 2021-11-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0015_auto_20211123_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='eventtime',
            field=models.TimeField(blank=True),
        ),
    ]
