# Generated by Django 2.2.1 on 2021-11-27 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0016_auto_20211127_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='capacity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='service',
            name='capacity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='eventtime',
            field=models.TimeField(blank=True),
        ),
    ]
