# Generated by Django 2.2.1 on 2021-11-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0017_auto_20211128_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerservice',
            name='owner',
            field=models.TextField(blank=True),
        ),
    ]
