# Generated by Django 2.2.1 on 2021-11-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0018_registerservice_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerevent',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registerservice',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registerevent',
            name='approved_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registerservice',
            name='approved_register',
            field=models.BooleanField(default=False),
        ),
    ]
