# Generated by Django 2.2.1 on 2021-12-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0020_auto_20211130_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
