# Generated by Django 2.2.1 on 2021-12-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0021_auto_20211203_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
