# Generated by Django 2.2.1 on 2021-12-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0022_auto_20211214_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Seminar', 'Seminar'), ('Conference', 'Conference'), ('Workshop', 'Workshop'), ('Themed parties', 'Themed party'), ('Webinar', 'Webinar'), ('Summit', 'Summit'), ('Music festival', 'Music festival')], default='Seminar', max_length=20),
        ),
    ]
