# Generated by Django 2.2.1 on 2021-12-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0023_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Seminar', 'Seminar'), ('Conference', 'Conference'), ('Workshop', 'Workshop'), ('Themed parties', 'Themed party'), ('Webinar', 'Webinar'), ('Summit', 'Summit'), ('Music festival', 'Music festival')], default='Seminar', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='uploads/event_pictures/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='picture',
            field=models.ImageField(upload_to='uploads/event_pictures/'),
        ),
    ]
