# Generated by Django 2.2.1 on 2022-01-01 15:53

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0024_auto_20211228_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='41.031964, 29.008841', max_length=63),
        ),
    ]
