# Generated by Django 2.2.1 on 2022-01-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0026_auto_20220101_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tempLocation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='tempLocation',
            field=models.TextField(blank=True),
        ),
    ]
