# Generated by Django 2.2.1 on 2022-01-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0037_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='isGiven',
            field=models.BooleanField(default=False),
        ),
    ]
