# Generated by Django 2.2.1 on 2022-01-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0038_service_isgiven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved',
            name='isOk',
            field=models.BooleanField(default=False),
        ),
    ]
