# Generated by Django 2.2.1 on 2022-04-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0039_auto_20220104_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='IsCancelled',
            field=models.BooleanField(default=False),
        ),
    ]
