# Generated by Django 2.2.1 on 2022-04-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0040_post_iscancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='IsCancelled',
            field=models.BooleanField(default=False),
        ),
    ]
