# Generated by Django 2.2.1 on 2022-05-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0044_auto_20220511_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcomment',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical comment'},
        ),
        migrations.AlterModelOptions(
            name='historicalpost',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical post'},
        ),
        migrations.AlterModelOptions(
            name='historicalservice',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical service'},
        ),
        migrations.AlterModelOptions(
            name='historicalservicecomment',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical service comment'},
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalpost',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalservicecomment',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
