# Generated by Django 2.2.1 on 2022-05-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0046_servicechart'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicechart',
            name='IsCancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicechart',
            name='isGiven',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicechart',
            name='isLate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicechart',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
