# Generated by Django 2.2.1 on 2022-05-23 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0049_servicechart_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='service',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
