# Generated by Django 2.2.1 on 2022-05-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0050_auto_20220523_1933'),
    ]

    operations = [
    ]
