# Generated by Django 2.2.1 on 2022-05-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventify', '0053_userchart'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservice',
            name='isPromoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='isPromoted',
            field=models.BooleanField(default=False),
        ),
    ]
